package gewichtstracker;
import java.util.List;

import javafx.fxml.FXML;
import javafx.scene.control.TableView;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.chart.LineChart;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.XYChart;

public class Controller {

    @FXML
    private TableView<GewichtEntry> entryTableView;

    @FXML
    private TableColumn<GewichtEntry, Integer> idColumn;

    @FXML
    private TableColumn<GewichtEntry, String> datumColumn;

    @FXML
    private TableColumn<GewichtEntry, Double> gewichtColumn;
    
    @FXML
    private LineChart<Number, Number> lineChart;

    private XYChart.Series<Number, Number> weightSeries;

    @FXML
    private TextField idTextField;

    @FXML
    private TextField datumTextField;

    @FXML
    private TextField gewichtTextField;

    private GewichtDAO gewichtDAO;

    public Controller() {
        gewichtDAO = new GewichtDAO();
        gewichtDAO.createTableIfNotExists();
    }

    @FXML
    private void initialize() {
        // Map die Spalten der TableView auf die Eigenschaften von GewichtEntry
        idColumn.setCellValueFactory(new PropertyValueFactory<>("id"));
        datumColumn.setCellValueFactory(new PropertyValueFactory<>("datum"));
        gewichtColumn.setCellValueFactory(new PropertyValueFactory<>("gewicht"));

        // Lade vorhandene Einträge in die TableView
        entryTableView.getItems().addAll(gewichtDAO.getAllEntries());

        // Füge einen Listener hinzu, um die Textfelder mit den Eintragsdaten zu füllen
        entryTableView.getSelectionModel().selectedItemProperty().addListener(
                (observable, oldValue, newValue) -> {
                    if (newValue != null) {
                        idTextField.setText(String.valueOf(newValue.getId()));
                        datumTextField.setText(newValue.getDatum());
                        gewichtTextField.setText(String.valueOf(newValue.getGewicht()));
                    }
                });
        // Initialisiere die LineChart-Daten
        weightSeries = new XYChart.Series<>();
        weightSeries.setName("Gewichtsverlauf");
        lineChart.getData().add(weightSeries);
        
        NumberAxis yAxis = (NumberAxis) lineChart.getYAxis();
        yAxis.setAutoRanging(false);
        yAxis.setLowerBound(90);
        yAxis.setUpperBound(130);

        // Aktualisiere die LineChart-Daten beim Start
        updateLineChart();
    }
    
    private void updateLineChart() {
        // Lösche alle Daten aus der LineChart-Serie
        weightSeries.getData().clear();

        // Füge die Einträge aus der Datenbank zur LineChart-Serie hinzu
        List<GewichtEntry> entries = gewichtDAO.getAllEntries();
        for (GewichtEntry entry : entries) {
            weightSeries.getData().add(new XYChart.Data<>(entry.getId(), entry.getGewicht()));
        }
    }


    @FXML
    private void handleAdd() {
        String datum = datumTextField.getText();
        double gewicht = Double.parseDouble(gewichtTextField.getText());

        GewichtEntry newEntry = new GewichtEntry(0, datum, gewicht); // id will be auto-generated by the database
        gewichtDAO.insert(newEntry);

        entryTableView.getItems().clear();
        entryTableView.getItems().addAll(gewichtDAO.getAllEntries());
        updateLineChart();

        clearTextFields();
    }

    @FXML
    private void handleUpdate() {
        int id = Integer.parseInt(idTextField.getText());
        String datum = datumTextField.getText();
        double gewicht = Double.parseDouble(gewichtTextField.getText());

        GewichtEntry updatedEntry = new GewichtEntry(id, datum, gewicht);
        gewichtDAO.update(updatedEntry);

        entryTableView.getItems().clear();
        entryTableView.getItems().addAll(gewichtDAO.getAllEntries());
        updateLineChart();
        clearTextFields();
    }

    @FXML
    private void handleDelete() {
        int id = Integer.parseInt(idTextField.getText());

        gewichtDAO.delete(id);

        entryTableView.getItems().clear();
        entryTableView.getItems().addAll(gewichtDAO.getAllEntries());
        updateLineChart();
        clearTextFields();
    }

    private void clearTextFields() {
        idTextField.clear();
        datumTextField.clear();
        gewichtTextField.clear();
    }
}
